# Generated by Django 5.2.11 on 2026-02-12 06:33

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_apartment_contact_building_contact_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение'),
        ),
    ]
